name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.20
  - requests=2.24.0
  - pip=20.3.3
  - mlflow=2.0.1
  - hydra-core=1.0.6
  - pip:
      - wandb==0.13.4
      - hydra-joblib-launcher==1.1.2
